name: Go Lint and Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        go:
          - '1.17'
          - '1.18'

    runs-on: ubuntu-latest

    name: Lint Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Lint Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: test -z $(gofmt -l .)

  build:
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.17'
          - '1.18'
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'

    runs-on: ${{ matrix.os }}
    name: Build and test Go ${{ matrix.go }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build and test Go ${{ matrix.go }} on ${{ matrix.os }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: go build ./...
      - run: go test ./...
