name: Go Lint and Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        go: ['1.24', '1.25']

    runs-on: ubuntu-latest

    name: Lint Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - name: Check formatting
        run: test -z "$(gofmt -l .)"
